/*
 * Kiseki OS - IOKit Mach Message Handler
 *
 * Intercepts Mach messages destined for IOKit kobject ports and
 * dispatches them to the appropriate IOKit handlers. This is the
 * equivalent of XNU's ipc_kobject_server() for IOKit objects.
 *
 * On XNU, when a message arrives at a port with a non-zero kobject_type,
 * ipc_kobject_server() intercepts it before normal queuing and routes
 * it to MIG-generated stubs. Here we implement that dispatch directly
 * in C, handling the same message IDs that IOKitLib sends.
 *
 * Supported kobject types:
 *   IKOT_MASTER_DEVICE  - IOKit master port (service matching)
 *   IKOT_IOKIT_OBJECT   - IOService port (open, get property)
 *   IKOT_IOKIT_CONNECT  - IOUserClient connection (call method, map memory)
 *
 * Reference: XNU osfmk/ipc/ipc_kobject.c, iokit/Kernel/IOUserClient.cpp
 */

#include <iokit/iokit_types.h>
#include <iokit/io_service.h>
#include <iokit/io_user_client.h>
#include <iokit/io_registry.h>
#include <iokit/io_memory_descriptor.h>
#include <mach/ipc.h>
#include <kern/kprintf.h>
#include <kern/thread.h>
#include <kern/pmm.h>

/* ============================================================================
 * IOKit Mach Message Structures
 *
 * These match the wire format that userland IOKitLib sends via Mach IPC.
 * On XNU these are generated by MIG; we define them manually.
 *
 * All messages follow the standard Mach IPC header format:
 *   mach_msg_header_t hdr;
 *   <body fields>
 *
 * Reply messages include:
 *   mach_msg_header_t hdr;
 *   kern_return_t     retcode;      // NDR not used in our implementation
 *   <reply fields>
 * ============================================================================ */

/*
 * IOServiceGetMatchingService(s) request:
 * The matching dictionary is serialised as a flat property table
 * sent inline after the header. For simplicity, we support matching
 * by IOClass name (a single string key "IOProviderClass").
 */
struct iokit_get_matching_request {
    mach_msg_header_t   hdr;
    uint32_t            match_key_count;        /* Number of match keys */
    /* Followed by: key-value pairs as:
     *   uint32_t key_len; char key[]; uint32_t val_type; <value>
     * We simplify: single IOProviderClass string match */
    char                class_name[128];        /* IOProviderClass value */
};

struct iokit_get_matching_reply {
    mach_msg_header_t   hdr;
    kern_return_t       retcode;
    mach_port_name_t    service_port;           /* Port name for matched service */
};

/*
 * IOServiceOpen request:
 * Opens a connection to an IOService, creating an IOUserClient.
 */
struct iokit_service_open_request {
    mach_msg_header_t   hdr;
    uint32_t            connect_type;           /* Driver-defined connection type */
};

struct iokit_service_open_reply {
    mach_msg_header_t   hdr;
    kern_return_t       retcode;
    mach_port_name_t    connect_port;           /* Port name for the user client */
};

/*
 * IOServiceClose request:
 * Closes a user client connection.
 */
struct iokit_service_close_request {
    mach_msg_header_t   hdr;
};

struct iokit_service_close_reply {
    mach_msg_header_t   hdr;
    kern_return_t       retcode;
};

/*
 * IOConnectCallMethod request:
 * Calls an external method on a user client.
 * Scalars and structure data are sent inline.
 */
struct iokit_call_method_request {
    mach_msg_header_t   hdr;
    uint32_t            selector;
    uint32_t            scalar_input_count;
    uint32_t            struct_input_size;
    uint32_t            scalar_output_count;    /* Expected output count */
    uint32_t            struct_output_size;      /* Expected output size */
    /*
     * Followed by:
     *   uint64_t scalar_input[scalar_input_count];
     *   uint8_t  struct_input[struct_input_size];
     */
    uint8_t             payload[];
};

struct iokit_call_method_reply {
    mach_msg_header_t   hdr;
    kern_return_t       retcode;
    uint32_t            scalar_output_count;
    uint32_t            struct_output_size;
    /*
     * Followed by:
     *   uint64_t scalar_output[scalar_output_count];
     *   uint8_t  struct_output[struct_output_size];
     */
    uint8_t             payload[];
};

/*
 * IOConnectMapMemory request:
 * Maps memory from a user client into the calling task.
 */
struct iokit_map_memory_request {
    mach_msg_header_t   hdr;
    uint32_t            memory_type;
    uint32_t            options;
};

struct iokit_map_memory_reply {
    mach_msg_header_t   hdr;
    kern_return_t       retcode;
    uint64_t            address;
    uint64_t            size;
};

/*
 * IOConnectUnmapMemory request:
 */
struct iokit_unmap_memory_request {
    mach_msg_header_t   hdr;
    uint32_t            memory_type;
    uint64_t            address;
};

struct iokit_unmap_memory_reply {
    mach_msg_header_t   hdr;
    kern_return_t       retcode;
};

/*
 * IORegistryEntryGetProperty request:
 */
struct iokit_get_property_request {
    mach_msg_header_t   hdr;
    char                key[IO_PROP_KEY_MAX];
};

struct iokit_get_property_reply {
    mach_msg_header_t   hdr;
    kern_return_t       retcode;
    uint32_t            value_type;             /* IO_PROP_STRING, etc. */
    uint32_t            value_size;
    uint8_t             value_data[256];         /* Serialised value */
};

/* ============================================================================
 * Helper: iokit_memcpy
 * ============================================================================ */

static void
iokit_memcpy(void *dst, const void *src, uint32_t len)
{
    uint8_t *d = (uint8_t *)dst;
    const uint8_t *s = (const uint8_t *)src;
    for (uint32_t i = 0; i < len; i++)
        d[i] = s[i];
}

static void
iokit_memset(void *dst, uint8_t val, uint32_t len)
{
    uint8_t *d = (uint8_t *)dst;
    for (uint32_t i = 0; i < len; i++)
        d[i] = val;
}

/* iokit_strcmp reserved for future use */

/* ============================================================================
 * Handler: kIOServiceGetMatchingServiceMsg / kIOServiceGetMatchingServicesMsg
 *
 * Userland sends: IOServiceGetMatchingService(masterPort, matchDict)
 *
 * We search the I/O Registry for a service matching the given class name.
 * On match, we create a kobject port for the service and send back
 * the port name (as a send right) in the reply.
 *
 * Reference: XNU is_io_service_get_matching_service()
 * ============================================================================ */

static IOReturn
iokit_handle_get_matching_service(
    const struct iokit_get_matching_request *req,
    struct iokit_get_matching_reply *reply,
    struct ipc_port *reply_port,
    struct task *caller_task,
    struct io_prop_table *match_props)
{
    (void)reply_port;   /* Reply sent by caller (iokit_kobject_server) */

    /*
     * Build a match table from the request.
     *
     * The caller provides a pre-allocated io_prop_table (from the scratch
     * page) to avoid placing the ~21 KB structure on the kernel stack.
     * On XNU, matching dictionaries are allocated from kalloc.
     */
    io_prop_table_init(match_props);

    /*
     * IOK-H1: Ensure class_name is NUL-terminated. The user-provided
     * buffer may not contain a NUL byte, causing unbounded string reads
     * in io_prop_set_string and kprintf. Force NUL at the last byte.
     */
    char safe_class_name[128];
    iokit_memcpy(safe_class_name, req->class_name, 127);
    safe_class_name[127] = '\0';

    if (safe_class_name[0] != '\0') {
        io_prop_set_string(match_props, kIOProviderClassKey, safe_class_name);
    }

    struct io_service *svc = io_service_get_matching_service(match_props);
    if (svc == NULL) {
        kprintf("[iokit_mach] GetMatchingService: no match for '%s'\n",
                safe_class_name);
        reply->retcode = kIOReturnNotFound;
        reply->service_port = MACH_PORT_NULL;
        return kIOReturnNotFound;
    }

    /*
     * The service needs a Mach port so userland can send messages to it.
     * If the service doesn't have one yet, allocate a kobject port.
     */
    struct io_registry_entry *entry = &svc->entry;
    if (entry->obj.iokit_port == NULL) {
        struct ipc_port *port = ipc_port_alloc();
        if (port == NULL) {
            reply->retcode = kIOReturnNoResources;
            reply->service_port = MACH_PORT_NULL;
            return kIOReturnNoResources;
        }
        port->kobject = svc;
        port->kobject_type = IKOT_IOKIT_OBJECT;
        entry->obj.iokit_port = port;
    }

    /*
     * Insert a SEND right to the service port into the caller's IPC space.
     */
    struct ipc_space *space = caller_task->ipc_space;
    struct ipc_port *svc_port = entry->obj.iokit_port;

    mach_port_name_t name;
    kern_return_t kr = ipc_port_allocate_name(space, svc_port,
                                              MACH_PORT_TYPE_SEND, &name);
    if (kr != KERN_SUCCESS) {
        reply->retcode = kIOReturnNoResources;
        reply->service_port = MACH_PORT_NULL;
        return kIOReturnNoResources;
    }

    /* IOK-M6: Use atomic increment for port refcount (SMP safety) */
    __atomic_fetch_add(&svc_port->refs, 1, __ATOMIC_RELAXED);

    reply->retcode = kIOReturnSuccess;
    reply->service_port = name;

    kprintf("[iokit_mach] GetMatchingService: matched '%s' -> port name %u\n",
            safe_class_name, name);

    return kIOReturnSuccess;
}

/* ============================================================================
 * Handler: kIOServiceOpenMsg
 *
 * Userland sends: IOServiceOpen(service, owningTask, type, &connect)
 *
 * Calls newUserClient() on the target IOService, which creates an
 * io_user_client. We then allocate a kobject port for the user client
 * and return it.
 *
 * Reference: XNU is_io_service_open_extended()
 * ============================================================================ */

static IOReturn
iokit_handle_service_open(
    struct io_service *service,
    const struct iokit_service_open_request *req,
    struct iokit_service_open_reply *reply,
    struct ipc_port *reply_port,
    struct task *caller_task)
{
    (void)reply_port;   /* Reply sent by caller (iokit_kobject_server) */

    const struct io_service_vtable *vt =
        (const struct io_service_vtable *)service->entry.obj.vtable;

    if (!vt->newUserClient) {
        kprintf("[iokit_mach] ServiceOpen: service has no newUserClient\n");
        reply->retcode = kIOReturnUnsupported;
        reply->connect_port = MACH_PORT_NULL;
        return kIOReturnUnsupported;
    }

    struct io_user_client *client = NULL;
    IOReturn ret = vt->newUserClient(service, caller_task,
                                     req->connect_type, &client);
    if (ret != kIOReturnSuccess || client == NULL) {
        kprintf("[iokit_mach] ServiceOpen: newUserClient failed (%d)\n", ret);
        reply->retcode = ret;
        reply->connect_port = MACH_PORT_NULL;
        return ret;
    }

    /*
     * Allocate a kobject port for the user client connection.
     */
    struct ipc_port *port = ipc_port_alloc();
    if (port == NULL) {
        io_user_client_close(client);
        reply->retcode = kIOReturnNoResources;
        reply->connect_port = MACH_PORT_NULL;
        return kIOReturnNoResources;
    }

    port->kobject = client;
    port->kobject_type = IKOT_IOKIT_CONNECT;
    client->service.entry.obj.iokit_port = port;

    /*
     * Insert SEND right into caller's IPC space.
     */
    struct ipc_space *space = caller_task->ipc_space;
    mach_port_name_t name;
    kern_return_t kr = ipc_port_allocate_name(space, port,
                                              MACH_PORT_TYPE_SEND, &name);
    if (kr != KERN_SUCCESS) {
        io_user_client_close(client);
        ipc_port_dealloc(port);
        reply->retcode = kIOReturnNoResources;
        reply->connect_port = MACH_PORT_NULL;
        return kIOReturnNoResources;
    }

    /* IOK-M6: Use atomic increment for port refcount (SMP safety) */
    __atomic_fetch_add(&port->refs, 1, __ATOMIC_RELAXED);

    reply->retcode = kIOReturnSuccess;
    reply->connect_port = name;

    kprintf("[iokit_mach] ServiceOpen: type %u -> connect port name %u\n",
            req->connect_type, name);

    return kIOReturnSuccess;
}

/* ============================================================================
 * Handler: kIOServiceCloseMsg
 *
 * Reference: XNU is_io_service_close()
 * ============================================================================ */

static IOReturn
iokit_handle_service_close(
    struct io_user_client *client,
    struct iokit_service_close_reply *reply)
{
    /*
     * IOK-M4: Save the port pointer BEFORE calling io_user_client_close(),
     * which may free/invalidate the client structure. Accessing
     * client->service.entry.obj.iokit_port after close is a use-after-free.
     */
    struct ipc_port *port = client->service.entry.obj.iokit_port;

    /* Invalidate the kobject port BEFORE close, to prevent
     * racing messages from being dispatched to a closed client */
    if (port != NULL) {
        port->kobject = NULL;
        port->kobject_type = IKOT_NONE;
    }

    IOReturn ret = io_user_client_close(client);

    reply->retcode = ret;

    kprintf("[iokit_mach] ServiceClose: ret %d\n", ret);
    return ret;
}

/* ============================================================================
 * Handler: kIOConnectCallMethodMsg
 *
 * Userland sends: IOConnectCallMethod(connect, selector, scalIn, scalInCnt,
 *                                      structIn, structInSz, ...)
 *
 * Reference: XNU is_io_connect_method()
 * ============================================================================ */

static IOReturn
iokit_handle_call_method(
    struct io_user_client *client,
    const uint8_t *msg_data,
    uint32_t msg_size,
    uint8_t *reply_buf,
    uint32_t *reply_size,
    uint8_t *scratch_buf)
{
    const struct iokit_call_method_request *req =
        (const struct iokit_call_method_request *)msg_data;

    /* Validate sizes */
    uint32_t hdr_size = (uint32_t)(
        sizeof(struct iokit_call_method_request));  /* up to payload[] */
    if (msg_size < hdr_size)
        return kIOReturnBadArgument;

    if (req->scalar_input_count > kIOExternalMethodScalarInputMax)
        return kIOReturnBadArgument;
    if (req->scalar_output_count > kIOExternalMethodScalarOutputMax)
        return kIOReturnBadArgument;
    if (req->struct_input_size > kIOExternalMethodStructureInputMax)
        return kIOReturnBadArgument;
    if (req->struct_output_size > kIOExternalMethodStructureOutputMax)
        return kIOReturnBadArgument;

    /*
     * IOK-C3: Use uint64_t for intermediate multiplication to prevent
     * 32-bit overflow. scalar_input_count is capped at 16, so the max
     * value is 16*8=128, but being explicit prevents future bugs.
     *
     * IOK-M7: Validate struct_output_size fits in the scratch buffer.
     * Scratch layout: [0..127] scalar_out (128 bytes),
     *                 [128..4095] struct_out (3968 bytes).
     * If struct_output_size > 3968, it would overflow the scratch page.
     */
    uint64_t scalar_in_bytes = (uint64_t)req->scalar_input_count * sizeof(uint64_t);
    uint64_t payload_needed64 = scalar_in_bytes + req->struct_input_size;
    if (payload_needed64 > 0xFFFFFFFFULL)
        return kIOReturnBadArgument;
    uint32_t payload_needed = (uint32_t)payload_needed64;

    if (msg_size < hdr_size + payload_needed)
        return kIOReturnBadArgument;

    /* IOK-M7: Validate struct_output_size fits in scratch page remainder */
    uint32_t scratch_struct_max = PAGE_SIZE
        - kIOExternalMethodScalarOutputMax * sizeof(uint64_t);  /* 4096 - 128 = 3968 */
    if (req->struct_output_size > scratch_struct_max)
        return kIOReturnBadArgument;

    /*
     * IOK-M8: Validate total reply payload fits in reply buffer (PAGE_SIZE).
     * Reply layout: iokit_call_method_reply header + scalar_out + struct_out.
     */
    uint64_t reply_payload64 = (uint64_t)req->scalar_output_count * sizeof(uint64_t)
                             + req->struct_output_size;
    uint64_t reply_total64 = sizeof(struct iokit_call_method_reply) + reply_payload64;
    if (reply_total64 > MACH_MSG_SIZE_MAX)
        return kIOReturnBadArgument;

    /* Set up input pointers into the request payload */
    const uint64_t *scalar_in = (const uint64_t *)req->payload;
    const void *struct_in = (req->struct_input_size > 0)
        ? (const void *)(req->payload + req->scalar_input_count * sizeof(uint64_t))
        : NULL;

    /* Set up output buffers in the reply */
    struct iokit_call_method_reply *rep =
        (struct iokit_call_method_reply *)reply_buf;

    uint32_t rep_hdr_size = (uint32_t)(
        sizeof(struct iokit_call_method_reply));

    /*
     * Use scratch page for temporary output buffers instead of stack.
     *
     * On XNU, these are allocated from kalloc/ipc_kmsg zones. We use
     * a caller-provided scratch page (4096 bytes) which is sufficient
     * for both scalar_out (16 * 8 = 128 bytes) and struct_out (up to
     * the remaining ~3968 bytes; kIOExternalMethodStructureOutputMax
     * is capped at page size).
     *
     * Layout within scratch page:
     *   [0 .. 127]    scalar_out  (16 x uint64_t)
     *   [128 .. 4095]  struct_out  (up to 3968 bytes)
     */
    uint64_t *scalar_out = (uint64_t *)scratch_buf;
    uint8_t *struct_out = scratch_buf +
        kIOExternalMethodScalarOutputMax * sizeof(uint64_t);
    iokit_memset(scalar_out, 0,
                 kIOExternalMethodScalarOutputMax * sizeof(uint64_t));
    /* Only zero the portion of struct_out that will actually be used */
    if (req->struct_output_size > 0)
        iokit_memset(struct_out, 0, req->struct_output_size);

    uint32_t actual_scalar_out = req->scalar_output_count;
    uint32_t actual_struct_out = req->struct_output_size;

    /* Build the method arguments */
    struct io_external_method_args args;
    args.scalarInput = scalar_in;
    args.scalarInputCount = req->scalar_input_count;
    args.structureInput = struct_in;
    args.structureInputSize = req->struct_input_size;
    args.scalarOutput = scalar_out;
    args.scalarOutputCount = actual_scalar_out;
    args.structureOutput = struct_out;
    args.structureOutputSize = actual_struct_out;

    IOReturn ret = io_user_client_call_method(client, req->selector, &args);

    /* Build reply */
    rep->retcode = ret;
    rep->scalar_output_count = actual_scalar_out;
    rep->struct_output_size = actual_struct_out;

    /* Copy output data into reply payload */
    uint32_t out_payload_size = actual_scalar_out * sizeof(uint64_t)
                              + actual_struct_out;
    if (out_payload_size > 0) {
        iokit_memcpy(rep->payload, scalar_out,
                     actual_scalar_out * sizeof(uint64_t));
        if (actual_struct_out > 0) {
            iokit_memcpy(rep->payload + actual_scalar_out * sizeof(uint64_t),
                         struct_out, actual_struct_out);
        }
    }

    *reply_size = rep_hdr_size + out_payload_size;

    return ret;
}

/* ============================================================================
 * Handler: kIOConnectMapMemoryMsg
 *
 * Userland sends: IOConnectMapMemory(connect, type, task, &addr, &size, opts)
 *
 * Reference: XNU is_io_connect_map_memory_into_task()
 * ============================================================================ */

static IOReturn
iokit_handle_map_memory(
    struct io_user_client *client,
    const struct iokit_map_memory_request *req,
    struct iokit_map_memory_reply *reply)
{
    uint64_t address = 0;
    uint64_t size = 0;

    IOReturn ret = io_user_client_map_memory(client,
                                             req->memory_type,
                                             req->options,
                                             &address, &size);

    reply->retcode = ret;
    reply->address = address;
    reply->size = size;

    kprintf("[iokit_mach] MapMemory: type %u, opts 0x%x -> addr 0x%lx, sz 0x%lx, ret %d\n",
            req->memory_type, req->options,
            (unsigned long)address, (unsigned long)size, ret);

    return ret;
}

/* ============================================================================
 * Handler: kIORegistryEntryGetPropertyMsg
 *
 * Userland sends: IORegistryEntryGetProperty(entry, key, &value)
 *
 * Reference: XNU is_io_registry_entry_get_property_bytes()
 * ============================================================================ */

static IOReturn
iokit_handle_get_property(
    struct io_service *service,
    const struct iokit_get_property_request *req,
    struct iokit_get_property_reply *reply)
{
    struct io_prop_table *props = &service->entry.prop_table;

    /*
     * IOK-H2: Ensure key is NUL-terminated. The user-provided buffer
     * may not contain a NUL byte, causing unbounded string reads in
     * io_prop_get.
     */
    char safe_key[IO_PROP_KEY_MAX];
    iokit_memcpy(safe_key, req->key, IO_PROP_KEY_MAX - 1);
    safe_key[IO_PROP_KEY_MAX - 1] = '\0';

    const struct io_prop_value *val =
        io_prop_get(props, safe_key);

    if (val == NULL) {
        reply->retcode = kIOReturnNotFound;
        reply->value_type = 0;
        reply->value_size = 0;
        return kIOReturnNotFound;
    }

    reply->retcode = kIOReturnSuccess;
    reply->value_type = val->type;

    switch (val->type) {
    case IO_PROP_STRING: {
        uint32_t len = 0;
        const char *s = val->u.string;
        while (s[len] && len < sizeof(reply->value_data) - 1)
            len++;
        iokit_memcpy(reply->value_data, s, len);
        reply->value_data[len] = '\0';
        reply->value_size = len + 1;
        break;
    }
    case IO_PROP_NUMBER:
        if (sizeof(reply->value_data) >= sizeof(uint64_t)) {
            iokit_memcpy(reply->value_data, &val->u.number, sizeof(uint64_t));
            reply->value_size = sizeof(uint64_t);
        }
        break;
    case IO_PROP_BOOL:
        reply->value_data[0] = val->u.boolean ? 1 : 0;
        reply->value_size = 1;
        break;
    case IO_PROP_DATA:
        if (val->u.data.length <= sizeof(reply->value_data)) {
            iokit_memcpy(reply->value_data, val->u.data.bytes,
                         val->u.data.length);
            reply->value_size = val->u.data.length;
        } else {
            reply->retcode = kIOReturnNoMemory;
            reply->value_size = 0;
        }
        break;
    default:
        reply->retcode = kIOReturnUnsupported;
        reply->value_size = 0;
        break;
    }

    return reply->retcode;
}

/* ============================================================================
 * iokit_kobject_server - Main IOKit kobject message dispatcher
 *
 * Called from mach_msg_trap() when the destination port has a non-zero
 * kobject_type that matches an IOKit type.
 *
 * This function:
 *   1. Reads the message from user memory
 *   2. Dispatches to the appropriate handler based on msgh_id
 *   3. Builds a reply message
 *   4. Sends the reply on the reply port (via ipc_port_send_kernel)
 *
 * Returns true if the message was handled (caller should NOT queue it).
 * Returns false if the message should be handled normally.
 *
 * @dest_port:    Destination port (kobject port)
 * @user_msg:     User-space message buffer
 * @send_size:    Size of user message
 * @reply_port:   Reply port (kernel object, already copyin'd)
 * @reply_type:   Post-copyin type for reply port
 * @caller_task:  The calling task
 *
 * Reference: XNU ipc_kobject_server()
 * ============================================================================ */

bool
iokit_kobject_server(struct ipc_port *dest_port,
                     const void *user_msg,
                     uint32_t send_size,
                     struct ipc_port *reply_port,
                     mach_msg_type_name_t reply_type,
                     struct task *caller_task)
{
    if (dest_port == NULL || user_msg == NULL)
        return false;

    uint32_t kotype = dest_port->kobject_type;
    void *kobject = dest_port->kobject;

    if (kotype == IKOT_NONE)
        return false;

    /* Read the message header to get the message ID */
    const mach_msg_header_t *hdr = (const mach_msg_header_t *)user_msg;
    uint32_t msg_id = hdr->msgh_id;



    (void)reply_type;   /* Reply disposition handled internally */

    /*
     * Reply + scratch buffer — allocated from the physical page allocator.
     *
     * On XNU, ipc_kobject_server() allocates reply messages from the
     * ipc_kmsg zone (backed by kalloc), and matching dictionaries from
     * kalloc. We don't have a general-purpose kernel heap, so we use
     * pmm_alloc_pages(3) to get 8 contiguous pages (32 KB):
     *
     *   Page 0:     reply buffer (up to MACH_MSG_SIZE_MAX = 4096 bytes)
     *   Page 1:     scratch buffer for CallMethod output temporaries
     *   Pages 2-7:  scratch space for io_prop_table (~21 KB) used by
     *               GetMatchingService, or unused for other message types
     *
     * This avoids >20 KB of stack buffers that caused kernel stack
     * overflow (kernel thread stacks are only 16 KB).
     */
    uint64_t buf_pa = pmm_alloc_pages(3);   /* order 3 = 8 pages = 32 KB */
    if (buf_pa == 0) {
        kprintf("[iokit_mach] failed to allocate reply buffer pages\n");
        return false;
    }
    uint8_t *reply_buf = (uint8_t *)buf_pa;
    uint8_t *scratch_buf = (uint8_t *)(buf_pa + PAGE_SIZE);
    struct io_prop_table *match_scratch =
        (struct io_prop_table *)(buf_pa + 2 * PAGE_SIZE);
    iokit_memset(reply_buf, 0, MACH_MSG_SIZE_MAX);
    uint32_t reply_size = 0;

    /*
     * Dispatch based on kobject type and message ID.
     *
     * We use a 'handled' flag + goto cleanup pattern to ensure the
     * dynamically allocated pages are always freed, even on error paths.
     */
    bool handled = true;

    switch (kotype) {

    /* ----------------------------------------------------------------
     * IKOT_MASTER_DEVICE — IOKit master port
     *
     * Handles IOServiceGetMatchingService(s)
     * ---------------------------------------------------------------- */
    case IKOT_MASTER_DEVICE:
        switch (msg_id) {
        case kIOServiceGetMatchingServiceMsg:
        case kIOServiceGetMatchingServicesMsg: {
            /*
             * IOK-C2: Validate send_size before casting user_msg.
             * Without this check, a short message could cause an
             * out-of-bounds kernel read when accessing request fields.
             */
            if (send_size < sizeof(struct iokit_get_matching_request)) {
                kprintf("[iokit_mach] GetMatching: msg too short (%u < %u)\n",
                        send_size,
                        (uint32_t)sizeof(struct iokit_get_matching_request));
                handled = false;
                goto cleanup;
            }
            struct iokit_get_matching_reply *rep =
                (struct iokit_get_matching_reply *)reply_buf;
            reply_size = sizeof(struct iokit_get_matching_reply);

            iokit_handle_get_matching_service(
                (const struct iokit_get_matching_request *)user_msg,
                rep, reply_port, caller_task, match_scratch);

            /* Set up reply header */
            rep->hdr.msgh_bits = MACH_MSGH_BITS(
                MACH_MSG_TYPE_MOVE_SEND_ONCE, 0);
            rep->hdr.msgh_size = reply_size;
            rep->hdr.msgh_remote_port = 0;  /* Filled by send_kernel */
            rep->hdr.msgh_local_port = 0;
            rep->hdr.msgh_id = msg_id + 100;  /* Reply ID = request + 100 */
            break;
        }
        default:
            kprintf("[iokit_mach] master port: unknown msg_id %u\n", msg_id);
            handled = false;
            goto cleanup;
        }
        break;

    /* ----------------------------------------------------------------
     * IKOT_IOKIT_OBJECT — IOService port
     *
     * Handles IOServiceOpen, GetProperty
     * ---------------------------------------------------------------- */
    case IKOT_IOKIT_OBJECT: {
        struct io_service *service = (struct io_service *)kobject;
        if (service == NULL) {
            kprintf("[iokit_mach] IOKIT_OBJECT port has NULL kobject\n");
            handled = false;
            goto cleanup;
        }

        switch (msg_id) {
        case kIOServiceOpenMsg: {
            /* IOK-C2: Validate send_size */
            if (send_size < sizeof(struct iokit_service_open_request)) {
                handled = false;
                goto cleanup;
            }
            struct iokit_service_open_reply *rep =
                (struct iokit_service_open_reply *)reply_buf;
            reply_size = sizeof(struct iokit_service_open_reply);

            iokit_handle_service_open(
                service,
                (const struct iokit_service_open_request *)user_msg,
                rep, reply_port, caller_task);

            rep->hdr.msgh_bits = MACH_MSGH_BITS(
                MACH_MSG_TYPE_MOVE_SEND_ONCE, 0);
            rep->hdr.msgh_size = reply_size;
            rep->hdr.msgh_remote_port = 0;
            rep->hdr.msgh_local_port = 0;
            rep->hdr.msgh_id = msg_id + 100;
            break;
        }
        case kIORegistryEntryGetPropertyMsg: {
            /* IOK-C2: Validate send_size */
            if (send_size < sizeof(struct iokit_get_property_request)) {
                handled = false;
                goto cleanup;
            }
            struct iokit_get_property_reply *rep =
                (struct iokit_get_property_reply *)reply_buf;
            reply_size = sizeof(struct iokit_get_property_reply);

            iokit_handle_get_property(
                service,
                (const struct iokit_get_property_request *)user_msg,
                rep);

            rep->hdr.msgh_bits = MACH_MSGH_BITS(
                MACH_MSG_TYPE_MOVE_SEND_ONCE, 0);
            rep->hdr.msgh_size = reply_size;
            rep->hdr.msgh_remote_port = 0;
            rep->hdr.msgh_local_port = 0;
            rep->hdr.msgh_id = msg_id + 100;
            break;
        }
        default:
            kprintf("[iokit_mach] IOKIT_OBJECT: unknown msg_id %u\n", msg_id);
            handled = false;
            goto cleanup;
        }
        break;
    }

    /* ----------------------------------------------------------------
     * IKOT_IOKIT_CONNECT — IOUserClient connection port
     *
     * Handles CallMethod, MapMemory, UnmapMemory, Close
     * ---------------------------------------------------------------- */
    case IKOT_IOKIT_CONNECT: {
        struct io_user_client *client = (struct io_user_client *)kobject;
        if (client == NULL) {
            kprintf("[iokit_mach] IOKIT_CONNECT port has NULL kobject\n");
            handled = false;
            goto cleanup;
        }

        switch (msg_id) {
        case kIOConnectCallMethodMsg: {
            reply_size = sizeof(struct iokit_call_method_reply);

            IOReturn ret = iokit_handle_call_method(
                client, (const uint8_t *)user_msg, send_size,
                reply_buf, &reply_size, scratch_buf);
            (void)ret;

            struct iokit_call_method_reply *rep =
                (struct iokit_call_method_reply *)reply_buf;
            rep->hdr.msgh_bits = MACH_MSGH_BITS(
                MACH_MSG_TYPE_MOVE_SEND_ONCE, 0);
            rep->hdr.msgh_size = reply_size;
            rep->hdr.msgh_remote_port = 0;
            rep->hdr.msgh_local_port = 0;
            rep->hdr.msgh_id = msg_id + 100;
            break;
        }
        case kIOConnectMapMemoryMsg: {
            /* IOK-C2: Validate send_size */
            if (send_size < sizeof(struct iokit_map_memory_request)) {
                handled = false;
                goto cleanup;
            }
            struct iokit_map_memory_reply *rep =
                (struct iokit_map_memory_reply *)reply_buf;
            reply_size = sizeof(struct iokit_map_memory_reply);

            iokit_handle_map_memory(
                client,
                (const struct iokit_map_memory_request *)user_msg,
                rep);

            rep->hdr.msgh_bits = MACH_MSGH_BITS(
                MACH_MSG_TYPE_MOVE_SEND_ONCE, 0);
            rep->hdr.msgh_size = reply_size;
            rep->hdr.msgh_remote_port = 0;
            rep->hdr.msgh_local_port = 0;
            rep->hdr.msgh_id = msg_id + 100;
            break;
        }
        case kIOServiceCloseMsg: {
            struct iokit_service_close_reply *rep =
                (struct iokit_service_close_reply *)reply_buf;
            reply_size = sizeof(struct iokit_service_close_reply);

            iokit_handle_service_close(client, rep);

            rep->hdr.msgh_bits = MACH_MSGH_BITS(
                MACH_MSG_TYPE_MOVE_SEND_ONCE, 0);
            rep->hdr.msgh_size = reply_size;
            rep->hdr.msgh_remote_port = 0;
            rep->hdr.msgh_local_port = 0;
            rep->hdr.msgh_id = msg_id + 100;
            break;
        }
        default:
            kprintf("[iokit_mach] IOKIT_CONNECT: unknown msg_id %u\n", msg_id);
            handled = false;
            goto cleanup;
        }
        break;
    }

    default:
        handled = false;
        goto cleanup;
    }

    /*
     * Send the reply message on the reply port.
     *
     * On XNU, ipc_kobject_server() builds a reply kmsg and returns it
     * to the caller (ipc_mqueue_send), which delivers it. We use
     * ipc_port_send_kernel() to enqueue directly.
     */
    if (reply_port != NULL && reply_size > 0) {
        mach_msg_return_t mr = ipc_port_send_kernel(
            reply_port,
            reply_buf,
            reply_size,
            NULL,                                   /* no reply-to-reply */
            MACH_MSG_TYPE_PORT_NONE,                /* no reply port type */
            MACH_MSG_TYPE_PORT_SEND_ONCE,           /* dest type for reply */
            NULL,                                   /* no OOL */
            0);                                     /* no OOL count */
        if (mr != MACH_MSG_SUCCESS) {
            kprintf("[iokit_mach] failed to send reply: %d\n", mr);
        }
    }

cleanup:
    pmm_free_pages(buf_pa, 3);  /* Free the 8-page allocation (order 3) */
    return handled;
}
